<?php
namespace AppBundle\SearchRepository;

use AppBundle\Model\ArticleSearch;
use Doctrine\ORM\EntityRepository;
use Elastica\Query\BoolQuery;
use Elastica\Query\Match;
use FOS\ElasticaBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends Repository
{
    public function search(ArticleSearch $articleSearch)
    {
        $boolQuery = new BoolQuery();
        $fieldQuery = new Match();
        $fieldQuery->setFieldQuery('article.title', $articleSearch->getTitle());
        $boolQuery->addShould($fieldQuery);

        return $this->find($boolQuery);
    }
}
